version: "3"

services:
  soketi:
    image: quay.io/soketi/soketi:1.6.1-16-debian
    ports:
      - "6001:6001"
      - "9601:9601"
    environment:
      SOKETI_DEBUG: "1"
      SOKETI_HOST: "0.0.0.0"
      SOKETI_PORT: "6001"
      SOKETI_METRICS_SERVER_PORT: "9601"
      SOKETI_DEFAULT_APP_ID: "help"
      SOKETI_DEFAULT_APP_KEY: "fghjhgfdfgh"
      SOKETI_DEFAULT_APP_SECRET: "sdfghjjhgf4567hgfdfghcvbn"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge